// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNT-oTSmvBfOHqFFgvqNR5ekiR-j7GuI',
    appId: '1:1083236123206:web:1484f9286af5aa03b1c047',
    messagingSenderId: '1083236123206',
    projectId: 'trektrak-6c6f2',
    authDomain: 'trektrak-6c6f2.firebaseapp.com',
    storageBucket: 'trektrak-6c6f2.appspot.com',
    measurementId: 'G-CVGR7ES2XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVwfixOoG1Y4FnWGQcmWBLD9EHV9Rrcgw',
    appId: '1:1083236123206:android:9091a19e734364e3b1c047',
    messagingSenderId: '1083236123206',
    projectId: 'trektrak-6c6f2',
    storageBucket: 'trektrak-6c6f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrGcX_oE7K-M2o9XxreRCKnDWClc2CmQ',
    appId: '1:1083236123206:ios:a4aa78ba907cbe1fb1c047',
    messagingSenderId: '1083236123206',
    projectId: 'trektrak-6c6f2',
    storageBucket: 'trektrak-6c6f2.appspot.com',
    iosClientId: '1083236123206-oqpjcq2n1vr7nqv1i39ofbc2a92qg9dt.apps.googleusercontent.com',
    iosBundleId: 'com.application.trekTrak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxrGcX_oE7K-M2o9XxreRCKnDWClc2CmQ',
    appId: '1:1083236123206:ios:a4aa78ba907cbe1fb1c047',
    messagingSenderId: '1083236123206',
    projectId: 'trektrak-6c6f2',
    storageBucket: 'trektrak-6c6f2.appspot.com',
    iosClientId: '1083236123206-oqpjcq2n1vr7nqv1i39ofbc2a92qg9dt.apps.googleusercontent.com',
    iosBundleId: 'com.application.trekTrak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiNT-oTSmvBfOHqFFgvqNR5ekiR-j7GuI',
    appId: '1:1083236123206:web:94809217130b9da6b1c047',
    messagingSenderId: '1083236123206',
    projectId: 'trektrak-6c6f2',
    authDomain: 'trektrak-6c6f2.firebaseapp.com',
    storageBucket: 'trektrak-6c6f2.appspot.com',
    measurementId: 'G-5CLH9WJZZY',
  );
}
